### ISSUE TITLE
Any method or feature can be used to plot candlestick graph like this？

### ISSUE THREAD

**Issue by kkonghao** [plotters-rs/plotters#203]
Hi，I am new guy i want to ask a question are there any methods or features can be used to plot this  candlestick graph  like this in plotters？

https://raw.githubusercontent.com/wiki/epezent/implot/screenshots3/candle.gif

thanks for your help

**Comment by 38** [comment]
Hi there, this is related to this issue #13. Hopefully we will get there when we have next major release. 

Currently, I think this is a dup issue to #13. So close it
