### ISSUE TITLE
[Feature Request] Make RGBColor `Copy`

### ISSUE THREAD

**Issue by vmalloc** [plotters-rs/plotters#205]
When building an abstraction over `plotters` I found myself needing to pass the colors around to parametrize plotting. It would be nice if they were `Copy` to help with that.

If that sounds reasonable I can craft a PR to add this.

Thanks in advance!

**Comment by shinmili** [comment]
Sounds like #185. It is already merged and published as a part of v0.3.1. Can you check it?
