### ISSUE TITLE
Support for wasm32-wasi target

### ISSUE THREAD

**Issue by bkolobara** [plotters-rs/plotters#219]
I ran into an issue while trying to compile plotters to WebAssembly.

Currently **any** `wasm32-*-*` target (e.g. `wasm32-unknown-unknown`, `wasm32-wasi, `wasm32-...`) is considered to be running inside the browsers and uses `wasm-bindgen` as a dependency.

But this is not always the case. In my case I'm trying to run it on the backend inside an application compiled to `wasm32-wasi` on [Wasmtime](https://github.com/bytecodealliance/wasmtime) and [Wasmer](https://github.com/wasmerio/wasmer). The issue is that `wasm-bindgen` doesn't work on this platforms because they are not browsers and the required wasm-bindgen imports are not satisfied.

Would plotters still work if we just treated `wasm32-wasi` as a non-wasm backend?

**Comment by tqwewe** [comment]
@38 I believe this issue should be reopened.

When trying to work with plotters on wasm32-wasi target, I get some errors:
```
error[E0432]: unresolved import `font_kit::source::SystemSource`
```

If I try adding font-kit with feature `source-fontconfig-default`, I get a different error:
```
error[E0432]: unresolved imports `libloading::Library`, `libloading::Symbol`
```

**Comment by tqwewe** [comment]
Nevermind, I got it working by removing the ttf and bitmap features. :+1:
