### ISSUE TITLE
[Feature Request] Pass the data range to `ValueFormatter::format`

### ISSUE THREAD

**Issue by koute** [plotters-rs/plotters#265]
The `ValueFormatter::format` method currently only takes a raw `value`; it would also be useful to have access to the actual range of values from `Ranged::range`. This would be useful e.g. in a situation where you want to put something like file sizes on the Y axis, and you'd use the range to figure out what unit to use (kilobytes, megabytes, etc.).

Not sure if there's a better way of doing it, there might be, but right now I've just put the range into a `thread_local` and access that from my `ValueFormatter::format`.

**Comment by 38** [comment]
Hi @koute,

Thanks for the using plotters! The suggestions sounds reasonable to me and I can imagine there some cases that we need additional information to stringify the values. 

Actually we can achieve this by simply make the` ValueFormatter ::format` accept a `self` parameter. The only problem is this may breaks some existing code if they implement their own coordinate types. So I think the better solution would be we introduce a new trait method which accepts `self` parameter and provides a default implementation that calls the legacy `format` function. 

Please let me know if you have any thoughts.

Thanks!

**Comment by 38** [comment]
Just implemented this feature. See example at [https://github.com/38/plotters/blob/master/examples/customized_coord.rs](https://github.com/38/plotters/blob/master/examples/customized_coord.rs) 

Please let me know if this works for you. If it does, I am going to publish this with the next minor release. 

Thanks!
