### ISSUE TITLE
Boxes range from -0.5 to 0.5 instead of 0 to 1.

### ISSUE THREAD

**Issue by ahcm** [plotters-rs/plotters#272]
Hi,

I use plotters in [hist-cli](https://github.com/ahcm/hist-cli/).

For some reason the boxes span -0.5 to +0.5.
I would like them to be 0 to 1.
echo 1 2 2 3 3 3 3 4 4 5  | tr ' ' '\n' | hist

How can I achieve than?

Best
Andy

**Comment by 38** [comment]
You need to use `into_segmented` method. Please let me know if you have further question.
