### ISSUE TITLE
Should I store the context across renders?

### ISSUE THREAD

**Issue by huntc** [plotters-rs/plotters#274]
Thanks for providing this great library!

For animation style scenarios, should we look to storing the chart context across multiple draw callbacks?

If so then what are the recommended means of storing the context and its associated objects? Do you have an example?

If not so then I presume that setting up the backend, drawing area and context is pretty quick.

I'm using the Yew library which'll can the `rendered` method each time a view is redrawn. The code I have so far:

```rust
    fn rendered(&mut self, _first_render: bool) {
        let canvas = self.canvas.cast::<HtmlCanvasElement>().unwrap();
        let backend = CanvasBackend::with_canvas_object(canvas).unwrap();
        let root = backend.into_drawing_area();
        let mut chart = ChartBuilder::on(&root)
            .x_label_area_size(30)
            .y_label_area_size(30)
            .build_cartesian_2d(-1f32..1f32, -1.2f32..1.2f32)
            .unwrap();

        root.fill(&TRANSPARENT).unwrap();

        chart
            .configure_mesh()
            .x_labels(3)
            .y_labels(3)
            .draw()
            .unwrap();

        chart
            .draw_series(LineSeries::new(
                (-50..=50)
                    .map(|x| x as f32 / 50.0)
                    .map(|x| (x, x.powf(2 as f32))),
                &RED,
            ))
            .unwrap();

        root.present().unwrap();
    }
```

**Comment by moehaque** [comment]
Hi @huntc ,
Did you manage to display the svg into the page? 
i would greatly  appreciate a peek , If you have any working example.
Thank you !

**Comment by huntc** [comment]
> Hi @huntc ,
> Did you manage to display the svg into the page?
> i would greatly appreciate a peek , If you have any working example.
> Thank you !

I abandoned the approach here as I didn’t find a resolution. I will close this issue.
