### ISSUE TITLE
How to draw indicator line / arbitrary text? 

### ISSUE THREAD

**Issue by wbrickner** [plotters-rs/plotters#278]
Hello,

I'd like to be able to indicate an exact time in a timeseries with a vertical colored line. 

I'd also like to be able to print multiline text at (x, y) coordinates on top of the chart, although that's not as important as my first goal. 

Is this possible in plotters? If so, how?

Thanks.

**Comment by 38** [comment]
Hi there, sorry for the delay 

Basically you can use [ChartContext::plotting_area](https://docs.rs/plotters/latest/plotters/chart/struct.ChartContext.html#method.plotting_area) method for a reference to the underlying drawing area - Then you can use [DrawingArea::draw](https://docs.rs/plotters/latest/plotters/drawing/struct.DrawingArea.html#method.draw) to draw any element on it.

Closing the issue, feel free to reopen or reply 
Thanks!.
