### ISSUE TITLE
[BUG] CandleStick does not utilize filled Style

### ISSUE THREAD

**Issue by NathanSWard** [plotters-rs/plotters#281]
**Describe the bug**
When creating a `CandleStick` such as:
```rust
let candle = CandleStick::new(
                    ...,
                    GREEN.filled(),
                    RED.filled(),
                    15,
                );
```
Even though the provided `ShapeStyle` is filled, the graph does not render the rectangle as filled.

**To Reproduce**
Use the current candlestick example and just add `.filled()` to the colors.

**Version Information**
`0.3.1`

**NOTE**
The logic is due to this: https://github.com/38/plotters/blob/72479a086a2f50b4c73d6e613cbf53b7aea604f5/src/element/candlestick.rs#L81
where `false` is always passed as the `fill` parameter for `draw_rect`.

**Comment by 38** [comment]
We are going to merge PR #290 and release new version. Closing the issue for now.
