### ISSUE TITLE
Build fail without freetype2

### ISSUE THREAD

**Issue by taeh98** [plotters-rs/plotters#282]
**Describe the bug**

When building the quick start example, you get the following error (on Ubuntu):

```
Compiling servo-fontconfig-sys v5.1.0
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`
```
....

```
checking for FREETYPE... no

  --- stderr
  configure: error: Package requirements (freetype2) were not met:

  No package 'freetype2' found

  Consider adjusting the PKG_CONFIG_PATH environment variable if you
  installed software in a non-standard prefix.

  Alternatively, you may set the environment variables FREETYPE_CFLAGS
  and FREETYPE_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
```

I fixed this error by running the following command, [as noted in a past issue](https://github.com/38/plotters/issues/10#issuecomment-500423482):

```
sudo apt-get install libfontconfig libfontconfig1-dev
```

Since this step is necessary for plotters to work at all, it should be added to the quick start instructions. If not for the above issue, I would not have been able to solve the problem and make plotters work. I'm obviously not sure about the architecture of plotters but if at all possible it would be better to use cargo dependencies to perform whatever functionality these libraries provide that plotters depends on.

**To Reproduce**

Attempt to build the quick start example without these packages installed on Ubuntu, and probably other Linux distros too

**Version Information**

plotters = "^0.3.1"

**Comment by Jaffa-Cakes** [comment]
Still having the same issue, except I am presented with a compiling error with `cmake` now. Cmake 3.20+ doesn't support the `--parallel` tag and plotters uses' it somewhere (maybe dependency or something).

I'll post an update with the logs. Running Amazon Linux 5.
