### ISSUE TITLE
Logarithm plot

### ISSUE THREAD

**Issue by maurokenny** [plotters-rs/plotters#291]
Hello,

What is the correct way to change the x and y axes to logarithm?

Thanks,

**Comment by 38** [comment]
Hi sorry for the delay, 

Please check the example https://github.com/plotters-rs/plotters/blob/93e65c43661e69dfbaa6f6b8893b53fadf4ca896/plotters/examples/tick_control.rs#L38

Use `range.log_scale` will change the plot to logarithm. 

Closing the issue and feel free to reopen it or ask any further question.
