### ISSUE TITLE
[BUG] Narrow peaks can exceed plot area

### ISSUE THREAD

**Issue by TomDeRybel** [plotters-rs/plotters#347]
**Describe the bug**
The line drawing seems to have an overshoot issue for very narrow peaks. These overshoots can reach beyond the drawing area.

Some examples of the observed behavior: 
- Very narrow peaks can exceed the drawing area, as shown in the screenshot. (35Hz peak)
- Very narrow peaks within the drawing area can generate artifacts where the displayed peak exceeds the data points. Note that no Y-data is larger than +30 dB, yet the peak goes higher. (1600Hz peak)
- When the peak is a few pixels wide, it nicely clips (or perhaps does not trigger the overshoot issue) (250Hz peak) 
- I am not sure the specified line width remains respected for these sharp peaks (could also be due to aliasing).

**To Reproduce**
Plot data with very narrow peaks that exceed the plot area. The peaks have to be steep enough that they are but a pixel wide or so when rendered. The attached code example includes data that illustrates these issues.

**Version Information**
plotters: git version
fltk: 1.3.6

![Screenshot_20220506_101251](https://user-images.githubusercontent.com/67321804/167093548-47726370-abba-4f05-9571-798250f58989.png)

[plotters_doodle.zip](https://github.com/plotters-rs/plotters/files/8638501/plotters_doodle.zip)

**Comment by Feng23** [comment]
Thank you for creating the issue! Could you share some minimal reproducible example code? That would help us debug.

**Comment by TomDeRybel** [comment]
I have added a working, minimal example project, as well as updated the description with additional information and observations.
Thank you for looking into this!

**Comment by 38** [comment]
Hi there, I've pushed a fix. Could you please confirm this is fixed. Thanks!

**Comment by TomDeRybel** [comment]
Thank you for your work! I can confirm that the issue is fixed.
