### ISSUE TITLE
[BUG] RGBAColor is private

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [plotters-rs/plotters#354]
**Describe the bug**
While `RGBColor` works fine, `RGBAColor` doesn't work and cannot be initialized because the object's tuple content are private; they use `pub(crate)`. Please make it public.

**To Reproduce**
Simple try to construct an RGBAColor object. You can't.

**Version Information**
0.3.1 from crates.io

**Comment by Feng23** [comment]
Please reopen the issue if the PR doesn't solve the issue.
