### ISSUE TITLE
[Feature Request] Add dashed lines

### ISSUE THREAD

**Issue by cavemanloverboy** [plotters-rs/plotters#357]
I recently tried to plot two lines of O(1.0) that were overlapping to within 1e-11. I thought it'd be great to plot one of them as a dashed line but found no feature to do so. Plotting each point as a dot with `Circle` worked okay, but would be great to have an enum or bool that is passed into `LineSeries` to generate dashed lines.

**Comment by facorread** [comment]
Duplicate of #321

**Comment by cavemanloverboy** [comment]
closing due to duplicate
