### ISSUE TITLE
Candlestick: support for plotting f64.

### ISSUE THREAD

**Issue by inconspicuous99** [plotters-rs/plotters#371]
### What is the feature ?
I would like to plot f64s with my candlesticks.

I would fix it myself, but I have no idea how.

### (Optional) Why this feature is useful and how people would use the feature ?
If they want to plot tiny cells.

### (Optional) Additional Information
```rust
the trait bound `for<'b> &'b plotters::element::CandleStick<Date<Local>, f64>: PointCollection<'b, (Date<Local>, f32)>` is not satisfied
the following implementations were found:
  <&'a plotters::element::CandleStick<X, Y> as PointCollection<'a, (X, Y)>>rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
context.rs(132, 24): required by a bound in `ChartContext::<'a, DB, CT>::draw_series`
```
```rust
    chart.draw_series(
        data.iter().map(|x| {
            CandleStick::new(parse_time(x.0), x.1, x.2, x.3, x.4, GREEN.filled(), RED, 15)
        }),
    )?;
```

**Comment by facorread** [comment]
@inconspicuous99 Would you be so kind to provide a [minimal, complete, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? From the error message, it may be possible that the input `data` has `f32` values, but the vertical range of the chart was built with `f64` values.

**Comment by inconspicuous99** [comment]
> @inconspicuous99 Would you be so kind to provide a [minimal, complete, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? From the error message, it may be possible that the input `data` has `f32` values, but the vertical range of the chart was built with `f64` values. An appropriate suffix should take care of that.

haha, you're right. apologies.

https://github.com/plotters-rs/plotters/blob/1330c79a2e7dff5a9d3758dc75da34ae36a36797/examples/stock.rs#L25
^ replacing
```rust
.build_cartesian_2d(from_date..to_date, 110f32..135f32)?;
```
with ```rust
.build_cartesian_2d(from_date..to_date, 110f64..135f64)?;
```
does solve the issue
