### ISSUE TITLE
[RFC] derive(Clone, Copy, Debug) everywhere to facilitate usage and contributions

### ISSUE THREAD

**Issue by facorread** [plotters-rs/plotters#372]
### What is the feature ?
The purpose of this RFC is to discuss the addition of `derive(Clone, Copy, Debug)` to as many structs and enums as possible.

This RFC does not aim to impose `Clone` or `Debug` on external types. It also does not aim to add `impl{}` anywhere. It just focuses on Plotters' own structs and enums, adding `derive` where the conditions already merit so.

I will try to work on a PR for this RFC.

### Why this feature is useful and how people would use the feature ?
- It facilitates understanding of crate operations by enabling users to introduce `dbg!()` and `print!({:})` in most Plotters objects.
- It facilitates users' debugging of their own code.
- The more users understand the operation of Plotters, the more potential contributors to the project.
- It prevents errors caused by the lack or excess of a `&` in user code; some of these errors can be frustrating. I can come up with an example if you want.

**Comment by facorread** [comment]
I took a closer look and concluded that adding a `derive` is, in practice, an API change.

If we derived `Clone` or `Debug` in public `struct`s in a stable release, and later introduced a bug fix or a nice new feature that is incompatible, we would not be able to remove the `derive` without versioning it as a compatibility-breaking change. Client crates and users of the library would need to refactor any code that relies on those traits.

I find this problem disappointing, but compatibility is obviously more important than introspection. Besides, everyone can always use debuggers to explore Plotters. They can also make personal forks if they want to use `Debug` or `Copy`.

See this [discussion](https://www.reddit.com/r/rust/comments/h0b2rv/comment/ftm58c2/?utm_source=reddit&utm_medium=web2x&context=3) for more information.

**Comment by AaronErhardt** [comment]
Deriving Copy could be considered an API change, but Clone and Debug shouldn't (unless they were removed). Also, I haven't seen a type where you couldn't implement those traits manually when the derive failed due to some internal changes.

**Comment by facorread** [comment]
From my review, a novel `Clone` or `Debug` would likely be removed in future revisions of `plotters` when we introduce a struct member of `dyn Fn` type, which is more likely than not. Formatting functions and legend keys already involve this type.
