### ISSUE TITLE
Re-export pixel format types when bitmap_backend feature is enabled

### ISSUE THREAD

**Issue by 38** [plotters-rs/plotters#377]
We need to re-export the pixel format types as well for usability.

See the following question in discussions.

--

Hello,
It's a silly thing but I can't figure out where to find RGBPixel for the bitmap back-end.

Recently, the back-ends were merged into plotters itself. To accommodate for this, I've modded my Cargo.toml as thus:
```
plotters = { git = "https://github.com/plotters-rs/plotters.git", default_features = false, features = ["line_series", "ttf", "bitmap_backend"] }
#plotters-bitmap = { git = "https://github.com/plotters-rs/plotters-bitmap.git" } # No longer needed.
```

And in my source file I have:
```
use plotters::prelude::*;
use plotters_bitmap::bitmap_pixel::RGBPixel;   // <-- This is WRONG.
//use plotters_bitmap::BitMapBackend; // Not needed anymore, is part of the prelude.
```

The issue is that I can't figure-out the path to RBGPixel now...

_Originally posted by @TomDeRybel in https://github.com/plotters-rs/plotters/discussions/376_

**Comment by FlareFlo** [comment]
Should the Pixel formats be exported under the prelude?

**Comment by 38** [comment]
> Should the Pixel formats be exported under the prelude?

Yes, I think so, as long as people use it from the prelude, that actually make sense. 

This also reminds me it would be nice if we can put all the automatically imported backends under some namespace. 

What's your idea on this?

Thanks!
