### ISSUE TITLE
[BUG] Semver breakage with plotters-backend 0.3.3

### ISSUE THREAD

**Issue by astraw** [plotters-rs/plotters#383]
Hi, a daily scheduled build on our CI server today is breaking after the release of `plotters-backend` 0.3.3. None of the relevant code has been changed since the previous (successful) builds.

```
error[E0004]: non-exhaustive patterns: `RotateAngle(_)` not covered
530   --> /builds/straw/rust-cam/.cargo-proj/registry/src/github.com-1ecc6299db9ec823/plotters-canvas-0.3.0/src/canvas.rs:248:28
531    |
532248 |         let degree = match style.transform() {
533    |                            ^^^^^^^^^^^^^^^^^ pattern `RotateAngle(_)` not covered
534    |
535   ::: /builds/straw/rust-cam/.cargo-proj/registry/src/github.com-1ecc6299db9ec823/plotters-backend-0.3.3/src/text.rs:139:5
536    |
537139 |     RotateAngle(f32),
538    |     ----------- not covered
539    |
540    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
541    = note: the matched value is of type `FontTransform`
```

**Comment by 38** [comment]
Thanks for reporting this breaking change. It turns out that we are merging breaking change to this minor release. 

Already revert the breaking change and please confirm plotters-backend v0.3.4 resolves your issue.

Thanks again for the bug!
Cheers!

**Comment by astraw** [comment]
Confirming plotters-backend 0.3.4 fixes the issue. Many thanks for your ultra-fast work and great to see releases from plotters coming again. :) Looking forward to new releases and thanks to all contributors.

**Comment by astraw** [comment]
I just realized that you may want to yank the plotters-backend v0.3.3 release so no one accidentally uses it.
