### ISSUE TITLE
[Feature Request] Allow usage of non-system fonts.

### ISSUE THREAD

**Issue by tk2217** [plotters-rs/plotters#417]
### What is the feature ?
Allow specifying of non-system font loaders when specifying fonts.

### Why this feature is useful and how people would use the feature ?
Currently, fonts can only be loaded with the `font-kit` crate's system loader, limiting you to fonts installed on your system.

**Comment by Monadic-Cat** [comment]
Actually, #311 added support for this. We just hadn't visibly documented that fact.
