### ISSUE TITLE
[BUG] `into_coord_trans()` not supported for chrono::DateTime

### ISSUE THREAD

**Issue by vpochapuis** [plotters-rs/plotters#421]
Hello everyone! 
I am new to the crate and I encountered a little issue:

**Describe the bug**
When using a Chart with `chrono::DateTime` on the X axis, its not possible to use the `into_coord_trans()` function of the ChartContext.

Trying to call the function gives the following error:
```
the method `into_coord_trans` exists for struct `plotters::chart::ChartContext<'_, plotters_canvas::CanvasBackend, plotters::prelude::Cartesian2d<plotters::prelude::RangedDateTime<chrono::DateTime<chrono::FixedOffset>>, plotters::coord::types::RangedCoordf64>>`, but its trait bounds were not satisfied
the following trait bounds were not satisfied:
`plotters::prelude::Cartesian2d<plotters::prelude::RangedDateTime<chrono::DateTime<chrono::FixedOffset>>, plotters::coord::types::RangedCoordf64>: plotters::coord::ReverseCoordTranslate`
```

**To Reproduce**
I am using the Canvas Backend, here is a made up example to trigger the issue:
```Rust
use plotters::prelude::*;
use plotters_canvas::CanvasBackend;


#[allow(clippy::similar_names)]
pub fn test_func(id: String) {
    let backend = CanvasBackend::new(&id).expect("cannot find canvas");
    let drawing_area = backend.into_drawing_area();
    drawing_area.fill(&WHITE);

    let time_0 = chrono::DateTime::parse_from_str(
        "1983 Apr 13 12:09:14.274 +0000",
        "%Y %b %d %H:%M:%S%.3f %z",
    )
    .unwrap();
    let time_1 = chrono::DateTime::parse_from_str(
        "1983 Apr 13 13:09:14.274 +0000",
        "%Y %b %d %H:%M:%S%.3f %z",
    )
    .unwrap();
    let time_2 = chrono::DateTime::parse_from_str(
        "1983 Apr 13 14:09:14.274 +0000",
        "%Y %b %d %H:%M:%S%.3f %z",
    )
    .unwrap();
    let times = vec![time_0, time_1, time_2];

    let chart_x_range = time_0..time_1;
    let chart_y_range = 0f64..2f64;

    let mut chart = ChartBuilder::on(&drawing_area)
        .margin(40i32)
        .caption::<&str, FontDesc>("Title", ("sans-serif", 20.0).into_font())
        .build_cartesian_2d(chart_x_range, chart_y_range)
        .unwrap();
    chart.configure_mesh().draw().unwrap();

    let data = times
        .iter()
        .enumerate()
        .map(|(index, x)| (*x, index as f64))
        .collect::<Vec<_>>();
    chart.draw_series(LineSeries::new(
        data.iter().map(|p| p.clone()),
        ShapeStyle {
            color: RGBAColor(255, 0, 0, 1.0),
            filled: true,
            stroke_width: 2,
        },
    ));
    drawing_area.present();
    let not_compiling = chart.into_coord_trans();
}
```

**Version Information**
```Toml
plotters = "0.3"
plotters-canvas = "0.3"
chrono = { version = "0.4", features = ["serde"]}
```

Is there anything I made wrong, and if yes could you let me know? Or is it a bug?

Thank you!

**Comment by xemwebe** [comment]
I have the same problem. I analyzed this problem for a while, with the aim to eventually provide a fix.

However, there is a major problem how coordinate transformations are handled internally. On the one hand, coordinates could be defined in any of a broad range of types. When converting this types to pixel ranges and back, the fixed type `usize` is used, with a 64 bit size on common x86_64 devices but which has only 32 bit for `wasm` targets. Therefore, conversion will fail if you choose `i128` or `u128` as coordinate system on most machine and for anything larger than `u32` for `wasm` targets (including chrono::DateTime).

**Comment by xemwebe** [comment]
I would be willing to work on a solution to this problem, e.g. by replacing `usize` by some generic type, but since this would require some major changes of the internals of coordinate representation, I would like to be sure that the maintainer of this library would approve such changes.

**Comment by vpochapuis** [comment]
Thank you for your willingness to help! 
As for a temporary solution for this issue, what I did is: 
- Convert the range from DateTime to i64 using `Chrono::DateTime::timestamp_millis`
- Give the Dataset as `timestamp_millis` too
- Use the x labels modifier to convert from milliseconds to the DataTime
It works, I didn't evaluate the performance impact, but at least it let me get the cursor position on the Chart!

![image](https://user-images.githubusercontent.com/75721408/194801340-f7c235c3-2ad5-4f03-8aa8-fa6f3e94f862.png)

**Comment by AaronErhardt** [comment]
> I would be willing to work on a solution to this problem, e.g. by replacing usize by some generic type, but since this would require some major changes of the internals of coordinate representation, I would like to be sure that the maintainer of this library would approve such changes.

This change would be very welcome. I suggest though to use the next-release-devel branch for this because this will likely include breaking changes.

**Comment by xemwebe** [comment]
Just to give a brief update: I have successfully implemented the `ReversibleRanged` trait for `TimeValue` types, which should be sufficient, but struggle with some other errors which seem unrelated to this, maybe due to basing the changes ont he `next-release-devel` branch. I'll keep you updated.

**Comment by xemwebe** [comment]
Pull Request #425 should fix this issue. Since I only had to add some trait implementation, no breaking change was required and the PR could be based on `master`.

**Comment by xemwebe** [comment]
PR #425 has been closed without merge, PR #426 fixes the same issues, but based on `next-release-devel`.

**Comment by xemwebe** [comment]
Merged to `next-release-devel`.

**Comment by AaronErhardt** [comment]
This is now fixed on master too and will be part of the next stable release.
