### ISSUE TITLE
[BUG] Panic in unsafe `fill_rect_fast`

### ISSUE THREAD

**Issue by agersant** [plotters-rs/plotters#461]
**Describe the bug**

When using Rust nightly compiler, attempting to draw a line is likely to cause a panic (depending on color / line coordinates):

```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x1ab590c7fd3', [redacted]\plotters-bitmap-0.3.2\src\bitmap_pixel\rgb.rs:215:29
```

The offending line is: https://github.com/plotters-rs/plotters/blob/acf5158c6f49b8bfe8a5431c64b0867a1a8b36d1/plotters-bitmap/src/bitmap_pixel/rgb.rs#L215

I believe the relevant Nightly change is https://github.com/rust-lang/rust/pull/98112, but this seems to be a plotters bug and not a rustc regression (from my limited understanding).

**To Reproduce**

```rust
use plotters::prelude::*;

fn main() {
    let mut backend = BitMapBackend::new("test.png", (256, 256));
    backend.draw_line((1, 0), (100, 0), &RED).unwrap();
}
```
Sample project: https://github.com/agersant/plotter-panic

**Version Information**
Plotters `0.3.4`

**Comment by nbdd0121** [comment]
That code does seem very broken:
* The transmute call is wrong, because `(u64, u64, u64)` does not have any layout guarantees.
* `ptr` comes from `*mut [u8; 24]`, which doesn't have the correct alignment for u64.

**Comment by pbdeuchler** [comment]
I'm hitting this as well, but only when plotting a line series with a certain number of data points

**Comment by noahdahlman** [comment]
I'm getting this as well, most of the examples in the docs fail when using bitmap backend. I tried this example in a sample project and always got a panic, no issues when switching to SVG backend. Only fails on nightly (I'm using `nightly-x86_64-unknown-linux-gnu` ), stable works fine.
```rust
use plotters::prelude::*;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut backend = BitMapBackend::new("1.png", (300, 200));
    backend.draw_rect((50, 50), (200, 150), &RED, true)?;
    backend.present()?;
    Ok(())
}
```

**Comment by jayvdb** [comment]
This now occurs on stable v1.70

**Comment by Berrysoft** [comment]
We need a new release.

**Comment by ktjd123** [comment]
I'm having error at `blend_rect_fast` 😭
