### ISSUE TITLE
How to hide top / right axis label?

### ISSUE THREAD

**Issue by divflex** [plotters-rs/plotters#471]
![image](https://user-images.githubusercontent.com/99337708/235415284-9606d11b-82cd-4bcd-80a3-6dc84a738550.png)

**Comment by bguo068** [comment]
It seems there is code in the gallery example. 
https://github.com/plotters-rs/plotters/blob/7030c7354de75d15824ca2dcc82b492efcd96297/plotters/examples/errorbar.rs#L23

**Comment by Feng23** [comment]
Thanks @bguo068!

@divflex I am closing the issue now. But feel free to reopen it if @bguo068 's comment doesn't solve your issue.
