### ISSUE TITLE
[BUG] Plot silently fails if file path does not have the correct file extension

### ISSUE THREAD

**Issue by samheuck** [plotters-rs/plotters#474]
**Describe the bug**
Expected: An error explaining that "plots/demo" is not a valid filename for the BitMapBackend. OR the image generates anyway, without a file extension.

Actual result: Code compiles and runs, but no image file is written to disk. In other words, a silent failure.

**To Reproduce**
```rs
const _PLOT_WIDTH: u32 = 1024;
const _PLOT_HEIGHT: u32 = 768;

fn _demo_plot() {
    let pi = std::f64::consts::PI;
    let plot = BitMapBackend::new("plots/demo", (_PLOT_WIDTH, _PLOT_HEIGHT)).into_drawing_area();
    plot.fill(&WHITE).unwrap();

    let mut chart = ChartBuilder::on(&plot)
        .build_cartesian_2d::<Range<f64>, Range<f64>>(-pi..pi, -1.2..1.2).unwrap();

    chart.draw_series(LineSeries::new(
        (-314..314).map(|x| x as f64/100.0).map(|x| (x, x.sin())), &RED)).unwrap();
}
```

**Version Information**
plotters = "0.3.4"

**Comment by 38** [comment]
Please check  https://github.com/plotters-rs/plotters/blob/7030c7354de75d15824ca2dcc82b492efcd96297/plotters/examples/chart.rs#L87 this example for detecting backend failures.
