### ISSUE TITLE
[BUG] `split_horizontally` & `split_vertically` produce wrong subplots positions when used in `evcxr`

### ISSUE THREAD

**Issue by wiseaidev** [plotters-rs/plotters#486]
## **Describe the bug**
Hello, friends! Well, first of all, thanks for this awesome crate. While building [this notebook](https://github.com/wiseaidev/rust-data-analysis/blob/main/6-plotters-tutorial-part-1.ipynb), I noticed that `split_horizontally` produces wrong subplots positions.

## **To Reproduce**
Go to [this notebook](https://github.com/wiseaidev/rust-data-analysis/blob/main/6-plotters-tutorial-part-1.ipynb) and scroll all the way to the `2. Using split_horizontally` section. The `split_horizontally` function is supposed to produce the same image as `split_evenly((1,2))`, amirite? However, it is not the case. Take a look at the screenshot below.
![Screenshot from 2023-07-18 19-16-46](https://github.com/plotters-rs/plotters/assets/62179149/200391f8-6881-4ec2-b535-7f5ec6ec410c)

## **Version Information**
```
:dep plotters = { version = "^0.3.5", default_features = false, features = ["evcxr", "all_series", "all_elements"] }
```

**Comment by alimm1995** [comment]
`.split_horizontally()` receives the size of the left section in pixels. That's why calling `.split_horizontally()` with a value of `2` doesn't really make sense. In your case, you want to do something like `.split_horizontally(320)`.

**Comment by wiseaidev** [comment]
Thanks for the help @AliMMehr! I first thought the argument is the number of columns in the graph, 2.
