### ISSUE TITLE
Not stable axis labels amount

### ISSUE THREAD

**Issue by serzhiio** [plotters-rs/plotters#51]
I noticed that in some cases (when chart is pretty small), lets say secondary coord with relative height 0.15 of main area height, there is situation when no labels are showing up even if there is range of only 0.0...0.1 and we have only 2 (and more) different values (0.05, 0.1). When we have only 1 value its showing correctly, if more nothing...
`.y_labels(5/10)`

**Comment by serzhiio** [comment]
Is it possible to firce plotters draw a minimum number of labels (2 or 3)?

**Comment by 38** [comment]
Let's find some way make the `x_labels` and `y_labels` semantics less confusing on partial axis

**Comment by 38** [comment]
Hi there, after years, I think the current plotters approach is acceptable as the number of label is the constraint for how many labels been emitted. 

Also in 0.3 we added the feature that allowing manually control what labels to emit.

So I think it's not an issue anymore and close this issue.
Please let me know if there's any concern. 

Thanks!
