### ISSUE TITLE
[Feature Request] Implement `LogScalable` for `usize` and `isize`

### ISSUE THREAD

**Issue by saona-raimundo** [plotters-rs/plotters#517]
### What is the feature ?
The `LogScalable` trait describes types that can be represented in logarithmic scale.
It is currently implemented for `uN`, `iN` and `fN` types, but not for `usize` and `isize`.

https://docs.rs/plotters/0.3.5/plotters/coord/combinators/trait.LogScalable.html

### Why this feature is useful and how people would use the feature ?
I was plotting some data that was usize and thought that it could be added. It is simply to have less compile errors when using the crate. 

### Additional Information
The PR would be two lines of code in
https://docs.rs/plotters/0.3.5/src/plotters/coord/ranged1d/combinators/logarithmic.rs.html#44
I am happy to do it.

**Comment by AaronErhardt** [comment]
Thanks for the report. I think this would indeed be a useful addition.

>  I am happy to do it.

If you could submit a PR, that'd be great :)
