### ISSUE TITLE
[BUG] currently nightly compiler cannot build plotters due to bug in pathfinder (simd)

### ISSUE THREAD

**Issue by jonaspleyer** [plotters-rs/plotters#554]
There is a bug in the most recent pathfinder version which currently prohibits building this package for with the newest nightly compiler. This means docs.rs will fail to build if a new version is to be published. There are multiple ways to deal with this bug:

1. Wait until the [bugfix](https://github.com/servo/pathfinder/pull/557) is pushed upstream
2. Do not build with the `ttf` feature (which enables the dependency). Check also #553 which enables all features for docs.rs specifically!
3. Try to roll back to another working version of pathfinder (I have not tested this yet).

My hope is that the bugfix is pushed upstream soon and a new version of pathfinder is released.

### Error message
```
rustup update nightly
cargo +nightly build
```
```
error[E0635]: unknown feature `stdsimd`
  --> /home/jonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.2/src/lib.rs:12:49
   |
12 | #![cfg_attr(pf_rustc_nightly, feature(simd_ffi, stdsimd))]
   |                                                 ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `pathfinder_simd` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by CDaut** [comment]
Any news on this? It appears the bugfix is pushed into upstream on the pathfinder repo.

**Comment by jonaspleyer** [comment]
I believe that there is no new verison published on crates.io yet. You can open an issue at their repo or wait until a new version is published. If you can, simply omit the `ttf` feature which enables the dependency in the first place.

**Comment by CDaut** [comment]
That works, thank you!

**Comment by atouchet** [comment]
A new version of pathfinder_simd has been published. This should hopefully be fixed now.

**Comment by jayvdb** [comment]
Yup, it is fixed.

**Comment by jonaspleyer** [comment]
I am closing this issue now.

**Comment by jonaspleyer** [comment]
I am closing this issue.
